language: go
services: mongodb

go:
  - 1.9.x

before_install:
  - go get -t -v ./...

install:
  - go get github.com/BurntSushi/toml gopkg.in/mgo.v2 github.com/gorilla/mux
script: 
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)