language: go

sudo: false

go:
  - 1.9.x

before_install:
  - go get github.com/BurntSushi/toml gopkg.in/mgo.v2
  - go get github.com/gorilla/mux

script: 
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

services: mongodb